apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    kcert.dev/ingress: "managed"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{ .Values.service.hostname }}
    secretName: {{ .Chart.Name }}
  rules:
  - host: {{ .Values.service.hostname }}
    http:
      paths:
      - path: /{{ .Chart.Name }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}