apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  #name: {{ .Chart.Name }}
  name: {{ .Values.service.name }}-ingress
  namespace: webapp
  labels:
    kcert.dev/ingress: "managed"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  tls:
  - hosts:
    - {{ .Values.service.hostname }}
    secretName: {{ .Values.service.hostname }}
  rules:
  - host: {{ .Values.service.hostname }}
    http:
      paths:
      - path: /{{ .Values.service.name }}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}